config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :trips
  devise_for :users
  root 'welcome#homepage'

  get 'index' => 'welcome#index'

  get 'about' => 'welcome#about'

  get 'test' => 'welcome#test'

  post 'create_itinerary' => 'trips#create_itinerary'

  post 'edit_itinerary' => 'trips#edit_itinerary'

  get 'delete_itinerary' => 'trips#delete_itinerary'

  post 'upload_photo' => 'trips#upload_photo'

  get 'all_photos' => 'trips#all_photos'

  get 'delete_photo' => 'trips#delete_photo'

  post 'create_partner' => 'trips#create_partner'

  get 'delete_partner' => 'trips#delete_partner'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord

	belongs_to :user
	has_many :itineraries
	has_many :photos
	has_many :partners
			
	mount_uploader :image, ImageUploader

	validates :name, presence: true, uniqueness: true
  validates :city, presence: true
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :all_trips, only: [:index, :create, :update, :destroy]
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  def create_partner
    Partner.create(name: params[:name], phone_number: params[:phone_number], email: params[:email], em_contact: params[:em_contact], em_number: params[:em_number], notes: params[:notes], image: params[:image], user_id: params[:user_id], trip_id: params[:trip_id])
    redirect_to :back
  end

  def delete_partner
    Partner.find(params[:id]).destroy
    redirect_to :back
  end

  def create_itinerary
    Itinerary.create(date: params[:date], activity: params[:activity], user_id: params[:user_id], trip_id: params[:trip_id])
    redirect_to :back
  end

  def edit_itinerary
    itinerary = Itinerary.find(params[:itinerary_id])
    itinerary.update(date: params[:date], activity: params[:activity])
    redirect_to itinerary.trip
  end

  def delete_itinerary
    Itinerary.find(params[:id]).destroy
    redirect_to :back
  end

  def upload_photo
    Photo.create(image: params[:image], user_id: params[:user_id], trip_id: params[:trip_id])
    redirect_to :back
  end

  def all_photos
    @photos = Photo.all
  end

  def delete_photo
    Photo.find(params[:id]).destroy
    redirect_to :back
  end

  def new
    @trip = Trip.new
    @contacts = Contact.all
  end

  def create
    @trip = Trip.create(trip_params)
    @contacts = Contact.all
  end

  def index
    @trips = Trip.where(:user_id => current_user.id)
    @contacts = Contact.all
  end

  def show
    @itinerary = Itinerary.new
    if params[:itinerary_id] != nil
      @itinerary = Itinerary.find(params[:itinerary_id])
    end
  end

  def update
    @trip.update(trip_params)
    @contacts = Contact.all
  end

 
  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def all_trips
      @trips = Trip.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :dates, :return_date, :city, :country, :departing_flight, :return_flight, :image, :user_id)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for @trip, remote: true, authenticity_token: true do |f| %>
  <div class="center">
    <div class="form-group">
      <%= f.text_field :name, placeholder: "Name This Trip. . ", autofocus: true, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_field :dates, id: "datetimepicker1", placeholder: "Departure Date", class:"form-control datetimepicker1" %>
    </div>

    <div class="form-group">
      <%= f.text_field :return_date, id: "datetimepicker1", placeholder: "Return Date", class:"form-control datetimepicker1" %>
    </div>

    <div class="form-group">
      <%= f.text_field :city, placeholder: "City", class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_field :country, placeholder: "Country", class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_field :departing_flight, placeholder: "Departing Flight #:", class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_field :return_flight, placeholder: "Return Flight #:", class:"form-control" %>
    </div>

    <div class="form_group">
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<div class="col-md-4 col-md-offset-4 trip_box center">
	<div class="trip-well center">
		<h3><%= link_to trip.name, trip, class: "trip-link" %></h3>
		<p><%= trip.city %>, <%= trip.country %></p>
		<p><%= link_to 'Edit', edit_trip_path(trip), remote: true %> |
	<%= link_to 'Destroy', trip, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %></p>
	</div>
</div>

app/views/trips/all_photos.html.erb
<% @photos.each do |photo| %>
	<%= image_tag photo.image, class: "show-images" %>
	<%= link_to "Delete Photo", delete_photo_path(id: photo.id), data: { confirm: 'Are You Sure?'} %>
<% end %>

app/views/trips/create.js.erb
$('#trips').html("<%= j (render @trips) %>");
$('#trip-form').slideUp(350);

app/views/trips/destroy.js.erb
$("trips").html("<%= j (render @trips) %>")

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>
<%= render 'addimage', trip: @trip %>


<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/edit.js.erb
$('#trip-form').html("<%= j (render 'form') %>");
$('#trip-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/trips/index.html.erb
<div class="row">
  <%= link_to new_trip_path, class:"add-trip-link", remote:true do %>
    <i class="fa fa-plane"></i> Add Trip
  <% end %>
  <div class="col-md-6 col-md-offset-3 center">
    <div id="trip-form" style="display:none;"></div>
  </div>
</div>

<h2 class="center">My Trips</h2>

<%= render @trips %>	

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/new.js.erb
$('#trip-form').html("<%= j (render 'form') %>");
$('#trip-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>


<div class="col-md-3 center trip_border">
	<h1><%= @trip.name %></h1>

	<h4><%= @trip.dates.to_date %></h4>

	<h4><%= @trip.city %>, <%= @trip.country %></h4>

	<% if @trip.departing_flight != "" %>
		<p>Departing flight #: <%= @trip.departing_flight %></p>
	<% end %>

	<% if @trip.return_flight != "" %>
		<p>Return flight #: <%= @trip.return_flight %></p>
	<% end %>
</div>

<div class="col-md-8 top-row center">
	<div class="row">
		<p class="right" id="add_partner"><i class="fa fa-plus "></i> Travel Partners</p>
	</div>
	<div id="partner"></div>

	<div id="inline" class="center row">
		<% @trip.partners.each do |partner| %>
				<div class="add-spacing">
					<p><%= image_tag partner.image, class:"partner_images" %></p>
					<h4><%= partner.name %></h4>
					<p><%= partner.phone_number %></p> 
					<p><%= partner.email %></p>
					<p><%= partner.notes %></p><br />
					<p>Emergency Contact:</p>
					<p><%= partner.em_contact %></p> 
					<p><%= partner.em_number %></p>
					<p><%= link_to "Delete", delete_partner_path(id: partner.id), data: { confirm: 'Are You Sure?' } %></p>
				</div>
		<% end %>	
	</div>
</div>

<div class="invisible center" id="new_partner">
	<%= form_tag(create_partner_path) do %>
		<%= text_area_tag :name, nil, placeholder: "Name" %> 
		<%= text_area_tag :phone_number, nil, placeholder: "Phone Number" %>
		<%= text_area_tag :email, nil, placeholder: "Email" %>
		<%= text_area_tag :em_contact, nil, placeholder: "Emergency Contact: Name" %>
		<%= text_area_tag :em_number, nil, placeholder: "Phone Number" %>
		<%= text_area_tag :notes, nil, placeholder: "Notes. . ." %>
		<%= hidden_field_tag :user_id, current_user.id %>
		<%= hidden_field_tag :trip_id, @trip.id %>
		<p class="far-right"><%= file_field_tag :image %></p>
		<%= submit_tag "Submit", class: "btn btn-primary" %>
	<% end %>
</div>

<div class="itinerary col-md-8"> 
	<div id="add_activity" class="row">
		<div id="add_activity">
			<p class="right add_activity_link"><i class="fa fa-plus"></i> Activities</p>
			<h4>Itinerary:</h4>
			<% @trip.itineraries.each do |itinerary| %>
				<p>
					<strong><%= itinerary.date %> :</strong> <%= itinerary.activity %>    
					<%= link_to "Delete", delete_itinerary_path(id: itinerary.id), data: { confirm: 'Remove Activity?'} %>		
				</p>
			<% end %>
		</div>
	</div>
	<div id="activity"></div>
</div>

<div class="invisible center" id="new_activity">
	<%= form_tag(create_itinerary_path) do %>
		<p><%= text_area_tag :date, nil, placeholder: "Date & Time" %></p> 
		<p><%= text_area_tag :activity, nil, placeholder: "Description" %></p>
		<p><%= hidden_field_tag :user_id, current_user.id %><%= hidden_field_tag :trip_id, @trip.id %><%= submit_tag "Submit", class: "btn btn-primary" %></p>
	<% end %>
</div>




<div class="col-md-8 col-md-offset-1">
	<div class="row">
		<p class="right" id="add_photo"><i class="fa fa-plus"></i> Photos</p>
	</div>
	<div id="photo"></div>
	<div class="row show-row">
		<p>
			<% @trip.photos.each do |photo| %>
				<%= link_to all_photos_path(id: @trip.id) do%>
					<%= image_tag photo.image, class: "show-images" %>
				<% end %>
			<% end %>
		</p>
	</div>
</div>

<div class="invisible center" id="photo_form">
	<%= form_tag(upload_photo_path) do %>
		<p class="far-right"><%= file_field_tag :image %></p>
		<%= hidden_field_tag :user_id, current_user.id %>
		<%= hidden_field_tag :trip_id, @trip.id %>
		<%= submit_tag "Submit", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/trips/update.js.erb
$('#trips').html("<%= j (render @trips) %>");
$('#trip-form').slideUp(350);