config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :trips
  devise_for :users
  root 'welcome#homepage'

  get 'index' => 'welcome#index'

  get 'about' => 'welcome#about'

  get 'test' => 'welcome#test'

  post 'create_itinerary' => 'trips#create_itinerary'

  post 'edit_itinerary' => 'trips#edit_itinerary'

  get 'delete_itinerary' => 'trips#delete_itinerary'

  post 'upload_photo' => 'trips#upload_photo'

  get 'all_photos' => 'trips#all_photos'

  get 'delete_photo' => 'trips#delete_photo'

  post 'create_partner' => 'trips#create_partner'

  get 'delete_partner' => 'trips#delete_partner'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord

	mount_uploader :image, ImageUploader

	belongs_to :user
	
	validates :name, presence: true
	validates :phone_number, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end


  # GET /contacts/new
  def new
    @contact = Contact.new

  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone_number, :email, :em_contact, :em_number, :notes, :image, :user_id, :trip_id)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.text_field :name, placeholder: "Name", autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.text_field :phone_number, placeholder: "Phone Number" %>
    </div>

    <div class="form-group">
      <%= f.text_field :email, placeholder: "Email Address" %>
    </div>

    <p>Emergency Contact:</p>

    <div class="form-group">
      <%= f.text_field :em_contact, placeholder: "Name" %>
    </div>

    <div class="form-group">
      <%= f.text_field :em_number, placeholder: "Phone Number" %>
    </div>

    <div class="form-group">
      <%= f.text_area :notes, placeholder: "Any Notes?" %>
    </div>

    <div class="form-group">
      <strong>Upload a photo</strong>
      <%= f.file_field :image %>
    </div>

    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>



    <div class="actions">
      <%= submit_tag "Create Contact", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Contact', new_contact_path %>

<h1>Contacts</h1>

<div class="container">
  <div class="row">
    <% @contacts.each do |contact| %>
      <div class="col-md-3 right">
        <p><%= image_tag contact.image %></p>
        <p><strong><%= link_to contact.name, contact %></strong></p>
        <p><%= contact.phone_number %></p>
        <p><%= contact.email %></p>
      </div>
    <% end %> 
  </div>
</div>


<br>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="col-md-3">
    <p><%= image_tag @contact.image %></p>

    <p><strong><%= @contact.name %></strong></p>

    <p><%= @contact.phone_number %></p>

    <p><%= @contact.email %></p> <br />

    <p>Emergency Contact:</p>
    <p><%= @contact.em_contact %></p> 

    <p><%= @contact.em_number %></p><br />

    <p>Notes:</p>
    <p><%= @contact.notes %></p>

    
    <p><%= link_to 'Edit', edit_contact_path(@contact) %> | <%= link_to 'Delete Contact', @contact, method: :delete, data: { confirm: 'Are you sure?' } %></p>

  </div>
</div>